# Generated by Django 2.2.17 on 2020-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
