# Generated by Django 4.2.16 on 2024-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0034_alter_action_id_alter_actiondocument_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_autocomplete',
            field=models.BooleanField(default=True, verbose_name='Autocomplete'),
        ),
    ]
