# Generated by Django 4.2.8 on 2024-01-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop_cms', '0020_alter_alias_id_alter_articlecategory_id_and_more'),
        ('Emailing', '0004_auto_20190328_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailing',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='coop_cms.newsletter'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
