# Generated by Django 4.2.8 on 2024-01-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop_cms', '0020_alter_alias_id_alter_articlecategory_id_and_more'),
        ('Emailing', '0005_alter_emailing_id_alter_emailing_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailing',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailing_set', to='coop_cms.newsletter'),
        ),
    ]
